# Generated by Django 5.2.5 on 2025-08-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='business',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='business',
            name='website',
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.business'),
            preserve_default=False,
        ),
    ]
