# Generated by Django 5.2.5 on 2025-08-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_business_created_at_remove_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='manager_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
